// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "WalletTopUp/internal/domain/entity"
	dto "WalletTopUp/internal/service/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletSvc is an autogenerated mock type for the WalletSvc type
type MockWalletSvc struct {
	mock.Mock
}

type MockWalletSvc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletSvc) EXPECT() *MockWalletSvc_Expecter {
	return &MockWalletSvc_Expecter{mock: &_m.Mock}
}

// ConfirmTx provides a mock function with given fields: ctx, tx
func (_m *MockWalletSvc) ConfirmTx(ctx context.Context, tx string) (*dto.ConfirmResult, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmTx")
	}

	var r0 *dto.ConfirmResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.ConfirmResult, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.ConfirmResult); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ConfirmResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletSvc_ConfirmTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmTx'
type MockWalletSvc_ConfirmTx_Call struct {
	*mock.Call
}

// ConfirmTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx string
func (_e *MockWalletSvc_Expecter) ConfirmTx(ctx interface{}, tx interface{}) *MockWalletSvc_ConfirmTx_Call {
	return &MockWalletSvc_ConfirmTx_Call{Call: _e.mock.On("ConfirmTx", ctx, tx)}
}

func (_c *MockWalletSvc_ConfirmTx_Call) Run(run func(ctx context.Context, tx string)) *MockWalletSvc_ConfirmTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWalletSvc_ConfirmTx_Call) Return(_a0 *dto.ConfirmResult, _a1 error) *MockWalletSvc_ConfirmTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletSvc_ConfirmTx_Call) RunAndReturn(run func(context.Context, string) (*dto.ConfirmResult, error)) *MockWalletSvc_ConfirmTx_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyTx provides a mock function with given fields: ctx, userId, amount, method
func (_m *MockWalletSvc) VerifyTx(ctx context.Context, userId uint, amount float64, method string) (*entity.Transaction, error) {
	ret := _m.Called(ctx, userId, amount, method)

	if len(ret) == 0 {
		panic("no return value specified for VerifyTx")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, float64, string) (*entity.Transaction, error)); ok {
		return rf(ctx, userId, amount, method)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, float64, string) *entity.Transaction); ok {
		r0 = rf(ctx, userId, amount, method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, float64, string) error); ok {
		r1 = rf(ctx, userId, amount, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletSvc_VerifyTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyTx'
type MockWalletSvc_VerifyTx_Call struct {
	*mock.Call
}

// VerifyTx is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uint
//   - amount float64
//   - method string
func (_e *MockWalletSvc_Expecter) VerifyTx(ctx interface{}, userId interface{}, amount interface{}, method interface{}) *MockWalletSvc_VerifyTx_Call {
	return &MockWalletSvc_VerifyTx_Call{Call: _e.mock.On("VerifyTx", ctx, userId, amount, method)}
}

func (_c *MockWalletSvc_VerifyTx_Call) Run(run func(ctx context.Context, userId uint, amount float64, method string)) *MockWalletSvc_VerifyTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(float64), args[3].(string))
	})
	return _c
}

func (_c *MockWalletSvc_VerifyTx_Call) Return(_a0 *entity.Transaction, _a1 error) *MockWalletSvc_VerifyTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletSvc_VerifyTx_Call) RunAndReturn(run func(context.Context, uint, float64, string) (*entity.Transaction, error)) *MockWalletSvc_VerifyTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletSvc creates a new instance of MockWalletSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletSvc {
	mock := &MockWalletSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
