// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "WalletTopUp/internal/domain/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactionCache is an autogenerated mock type for the TransactionCache type
type MockTransactionCache struct {
	mock.Mock
}

type MockTransactionCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionCache) EXPECT() *MockTransactionCache_Expecter {
	return &MockTransactionCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTransactionCache) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTransactionCache_Expecter) Delete(ctx interface{}, id interface{}) *MockTransactionCache_Delete_Call {
	return &MockTransactionCache_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTransactionCache_Delete_Call) Run(run func(ctx context.Context, id string)) *MockTransactionCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionCache_Delete_Call) Return(_a0 error) *MockTransactionCache_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionCache_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockTransactionCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockTransactionCache) Get(ctx context.Context, id string) (*entity.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTransactionCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTransactionCache_Expecter) Get(ctx interface{}, id interface{}) *MockTransactionCache_Get_Call {
	return &MockTransactionCache_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockTransactionCache_Get_Call) Run(run func(ctx context.Context, id string)) *MockTransactionCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionCache_Get_Call) Return(_a0 *entity.Transaction, _a1 error) *MockTransactionCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionCache_Get_Call) RunAndReturn(run func(context.Context, string) (*entity.Transaction, error)) *MockTransactionCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, tx
func (_m *MockTransactionCache) Set(ctx context.Context, tx *entity.Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockTransactionCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *entity.Transaction
func (_e *MockTransactionCache_Expecter) Set(ctx interface{}, tx interface{}) *MockTransactionCache_Set_Call {
	return &MockTransactionCache_Set_Call{Call: _e.mock.On("Set", ctx, tx)}
}

func (_c *MockTransactionCache_Set_Call) Run(run func(ctx context.Context, tx *entity.Transaction)) *MockTransactionCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Transaction))
	})
	return _c
}

func (_c *MockTransactionCache_Set_Call) Return(_a0 error) *MockTransactionCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionCache_Set_Call) RunAndReturn(run func(context.Context, *entity.Transaction) error) *MockTransactionCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionCache creates a new instance of MockTransactionCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionCache {
	mock := &MockTransactionCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
