// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager struct {
	mock.Mock
}

type MockTxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxManager) EXPECT() *MockTxManager_Expecter {
	return &MockTxManager_Expecter{mock: &_m.Mock}
}

// GetTx provides a mock function with given fields: ctx
func (_m *MockTxManager) GetTx(ctx context.Context) *gorm.DB {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTx")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// MockTxManager_GetTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTx'
type MockTxManager_GetTx_Call struct {
	*mock.Call
}

// GetTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTxManager_Expecter) GetTx(ctx interface{}) *MockTxManager_GetTx_Call {
	return &MockTxManager_GetTx_Call{Call: _e.mock.On("GetTx", ctx)}
}

func (_c *MockTxManager_GetTx_Call) Run(run func(ctx context.Context)) *MockTxManager_GetTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTxManager_GetTx_Call) Return(_a0 *gorm.DB) *MockTxManager_GetTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxManager_GetTx_Call) RunAndReturn(run func(context.Context) *gorm.DB) *MockTxManager_GetTx_Call {
	_c.Call.Return(run)
	return _c
}

// WithinTransaction provides a mock function with given fields: ctx, fn
func (_m *MockTxManager) WithinTransaction(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxManager_WithinTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTransaction'
type MockTxManager_WithinTransaction_Call struct {
	*mock.Call
}

// WithinTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockTxManager_Expecter) WithinTransaction(ctx interface{}, fn interface{}) *MockTxManager_WithinTransaction_Call {
	return &MockTxManager_WithinTransaction_Call{Call: _e.mock.On("WithinTransaction", ctx, fn)}
}

func (_c *MockTxManager_WithinTransaction_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockTxManager_WithinTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockTxManager_WithinTransaction_Call) Return(_a0 error) *MockTxManager_WithinTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxManager_WithinTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockTxManager_WithinTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxManager creates a new instance of MockTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxManager {
	mock := &MockTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
