// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "WalletTopUp/internal/domain/entity"
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	repository "WalletTopUp/internal/domain/repository"
)

// MockTxRepo is an autogenerated mock type for the TxRepo type
type MockTxRepo struct {
	mock.Mock
}

type MockTxRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxRepo) EXPECT() *MockTxRepo_Expecter {
	return &MockTxRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx
func (_m *MockTxRepo) Create(ctx context.Context, tx entity.Transaction) (*entity.Transaction, error) {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Transaction) (*entity.Transaction, error)); ok {
		return rf(ctx, tx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Transaction) *entity.Transaction); ok {
		r0 = rf(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Transaction) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTxRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTxRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx entity.Transaction
func (_e *MockTxRepo_Expecter) Create(ctx interface{}, tx interface{}) *MockTxRepo_Create_Call {
	return &MockTxRepo_Create_Call{Call: _e.mock.On("Create", ctx, tx)}
}

func (_c *MockTxRepo_Create_Call) Run(run func(ctx context.Context, tx entity.Transaction)) *MockTxRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Transaction))
	})
	return _c
}

func (_c *MockTxRepo_Create_Call) Return(_a0 *entity.Transaction, _a1 error) *MockTxRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTxRepo_Create_Call) RunAndReturn(run func(context.Context, entity.Transaction) (*entity.Transaction, error)) *MockTxRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function with given fields: ctx, id
func (_m *MockTxRepo) FindById(ctx context.Context, id string) (*entity.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entity.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTxRepo_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockTxRepo_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTxRepo_Expecter) FindById(ctx interface{}, id interface{}) *MockTxRepo_FindById_Call {
	return &MockTxRepo_FindById_Call{Call: _e.mock.On("FindById", ctx, id)}
}

func (_c *MockTxRepo_FindById_Call) Run(run func(ctx context.Context, id string)) *MockTxRepo_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTxRepo_FindById_Call) Return(_a0 *entity.Transaction, _a1 error) *MockTxRepo_FindById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTxRepo_FindById_Call) RunAndReturn(run func(context.Context, string) (*entity.Transaction, error)) *MockTxRepo_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, tx
func (_m *MockTxRepo) Update(ctx context.Context, tx entity.Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTxRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tx entity.Transaction
func (_e *MockTxRepo_Expecter) Update(ctx interface{}, tx interface{}) *MockTxRepo_Update_Call {
	return &MockTxRepo_Update_Call{Call: _e.mock.On("Update", ctx, tx)}
}

func (_c *MockTxRepo_Update_Call) Run(run func(ctx context.Context, tx entity.Transaction)) *MockTxRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Transaction))
	})
	return _c
}

func (_c *MockTxRepo_Update_Call) Return(_a0 error) *MockTxRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxRepo_Update_Call) RunAndReturn(run func(context.Context, entity.Transaction) error) *MockTxRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: tx
func (_m *MockTxRepo) WithTx(tx *gorm.DB) repository.TxRepo {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.TxRepo
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.TxRepo); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.TxRepo)
		}
	}

	return r0
}

// MockTxRepo_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockTxRepo_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockTxRepo_Expecter) WithTx(tx interface{}) *MockTxRepo_WithTx_Call {
	return &MockTxRepo_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockTxRepo_WithTx_Call) Run(run func(tx *gorm.DB)) *MockTxRepo_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *MockTxRepo_WithTx_Call) Return(_a0 repository.TxRepo) *MockTxRepo_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxRepo_WithTx_Call) RunAndReturn(run func(*gorm.DB) repository.TxRepo) *MockTxRepo_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxRepo creates a new instance of MockTxRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxRepo {
	mock := &MockTxRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
