// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "WalletTopUp/internal/domain/entity"
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	repository "WalletTopUp/internal/domain/repository"
)

// MockWalletRepo is an autogenerated mock type for the WalletRepo type
type MockWalletRepo struct {
	mock.Mock
}

type MockWalletRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletRepo) EXPECT() *MockWalletRepo_Expecter {
	return &MockWalletRepo_Expecter{mock: &_m.Mock}
}

// IncreaseBalance provides a mock function with given fields: ctx, userId, amount
func (_m *MockWalletRepo) IncreaseBalance(ctx context.Context, userId uint, amount float64) (*entity.Wallet, error) {
	ret := _m.Called(ctx, userId, amount)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseBalance")
	}

	var r0 *entity.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, float64) (*entity.Wallet, error)); ok {
		return rf(ctx, userId, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, float64) *entity.Wallet); ok {
		r0 = rf(ctx, userId, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, float64) error); ok {
		r1 = rf(ctx, userId, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepo_IncreaseBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseBalance'
type MockWalletRepo_IncreaseBalance_Call struct {
	*mock.Call
}

// IncreaseBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uint
//   - amount float64
func (_e *MockWalletRepo_Expecter) IncreaseBalance(ctx interface{}, userId interface{}, amount interface{}) *MockWalletRepo_IncreaseBalance_Call {
	return &MockWalletRepo_IncreaseBalance_Call{Call: _e.mock.On("IncreaseBalance", ctx, userId, amount)}
}

func (_c *MockWalletRepo_IncreaseBalance_Call) Run(run func(ctx context.Context, userId uint, amount float64)) *MockWalletRepo_IncreaseBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(float64))
	})
	return _c
}

func (_c *MockWalletRepo_IncreaseBalance_Call) Return(_a0 *entity.Wallet, _a1 error) *MockWalletRepo_IncreaseBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepo_IncreaseBalance_Call) RunAndReturn(run func(context.Context, uint, float64) (*entity.Wallet, error)) *MockWalletRepo_IncreaseBalance_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: tx
func (_m *MockWalletRepo) WithTx(tx *gorm.DB) repository.WalletRepo {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.WalletRepo
	if rf, ok := ret.Get(0).(func(*gorm.DB) repository.WalletRepo); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.WalletRepo)
		}
	}

	return r0
}

// MockWalletRepo_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockWalletRepo_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockWalletRepo_Expecter) WithTx(tx interface{}) *MockWalletRepo_WithTx_Call {
	return &MockWalletRepo_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockWalletRepo_WithTx_Call) Run(run func(tx *gorm.DB)) *MockWalletRepo_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *MockWalletRepo_WithTx_Call) Return(_a0 repository.WalletRepo) *MockWalletRepo_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletRepo_WithTx_Call) RunAndReturn(run func(*gorm.DB) repository.WalletRepo) *MockWalletRepo_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletRepo creates a new instance of MockWalletRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletRepo {
	mock := &MockWalletRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
