// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MockWalletHandler is an autogenerated mock type for the WalletHandler type
type MockWalletHandler struct {
	mock.Mock
}

type MockWalletHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletHandler) EXPECT() *MockWalletHandler_Expecter {
	return &MockWalletHandler_Expecter{mock: &_m.Mock}
}

// ConfirmTx provides a mock function with given fields: c
func (_m *MockWalletHandler) ConfirmTx(c *gin.Context) {
	_m.Called(c)
}

// MockWalletHandler_ConfirmTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmTx'
type MockWalletHandler_ConfirmTx_Call struct {
	*mock.Call
}

// ConfirmTx is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockWalletHandler_Expecter) ConfirmTx(c interface{}) *MockWalletHandler_ConfirmTx_Call {
	return &MockWalletHandler_ConfirmTx_Call{Call: _e.mock.On("ConfirmTx", c)}
}

func (_c *MockWalletHandler_ConfirmTx_Call) Run(run func(c *gin.Context)) *MockWalletHandler_ConfirmTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockWalletHandler_ConfirmTx_Call) Return() *MockWalletHandler_ConfirmTx_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWalletHandler_ConfirmTx_Call) RunAndReturn(run func(*gin.Context)) *MockWalletHandler_ConfirmTx_Call {
	_c.Run(run)
	return _c
}

// VerifyTx provides a mock function with given fields: c
func (_m *MockWalletHandler) VerifyTx(c *gin.Context) {
	_m.Called(c)
}

// MockWalletHandler_VerifyTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyTx'
type MockWalletHandler_VerifyTx_Call struct {
	*mock.Call
}

// VerifyTx is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockWalletHandler_Expecter) VerifyTx(c interface{}) *MockWalletHandler_VerifyTx_Call {
	return &MockWalletHandler_VerifyTx_Call{Call: _e.mock.On("VerifyTx", c)}
}

func (_c *MockWalletHandler_VerifyTx_Call) Run(run func(c *gin.Context)) *MockWalletHandler_VerifyTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockWalletHandler_VerifyTx_Call) Return() *MockWalletHandler_VerifyTx_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWalletHandler_VerifyTx_Call) RunAndReturn(run func(*gin.Context)) *MockWalletHandler_VerifyTx_Call {
	_c.Run(run)
	return _c
}

// NewMockWalletHandler creates a new instance of MockWalletHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletHandler {
	mock := &MockWalletHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
